apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
spec:
  replicas: {REPLICAS}
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/nodegroup
                    operator: In
                    values:
                      - hopara
                      - hopara-green
                      - hopara-blue
                      - hopara-green-spot
                      - hopara-blue-spot
      containers:
      - name: template
        image: {IMAGE}
        env:
        - name: AWS_APP_ACCESS_KEY_ID
          value: {AWS_APP_ACCESS_KEY_ID}
        - name: AWS_APP_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: template
              key: awsSecretKey
        - name: DATASET_URL
          value: http://dataset
        - name: RESOURCE_URL
          value: http://resource-api
        - name: AUTH_JWKS_URI
          value: {AUTH_JWKS_URI}
        - name: AUTH_JWT_ISSUER
          value: {AUTH_JWT_ISSUER}
        - name: AUTH_ENABLED
          value: "true"
