apiVersion: v1
kind: Service
metadata:
  name: template
spec:
  type: NodePort
  selector:
    app: template
  ports:
    - name: http
      port: 80
      targetPort: 8089
  internalTrafficPolicy: Local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: template
  annotations:
    alb.ingress.kubernetes.io/group.name: {BALANCER_GROUP_NAME}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:275067427606:certificate/e96dabfa-71ff-47df-a255-6dc930fda7c1
spec:
  ingressClassName: alb
  rules:
    - host: {BALANCER_HOST}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: template
              port:
                number: 80
