import { isString } from 'lodash/fp'
import { notifyError } from '@hopara/rum'
import { HttpError, NotFoundError } from '@hopara/http-client'

function shouldIgnoreErrorMessage(message:string) {
  // Ignoring error generated by mapbox-gl
  // https://github.com/mapbox/mapbox-gl-js/blob/fd2045fd6aef55d9265c9a4c43fb48b294289482/src/util/ajax.js#L183
  return message === 'Error: Failed to fetch' || (message.includes('AJAXError') && message.includes('api.maptiler.com'))
}

export function overrideConsole(window) {
  const oldConsoleWarn = window.console.warn
  window.console.warn = function(message?: any, ...optionalParams: any[]) {
    if (isString(message) && message.includes('returned the root state when called')) {
      return
    }
    oldConsoleWarn(message, ...optionalParams)
  }

  const oldConsoleError = window.console.error
  window.console.error = function(message?: any, ...optionalParams: any[]) {
    const stringMessage = message + ''
    if (shouldIgnoreErrorMessage(stringMessage)) return

    const error = message instanceof Error || message instanceof HttpError || message instanceof NotFoundError ? message : new Error(message)
    notifyError(error, (error as any).context)
    oldConsoleError(message, ...optionalParams)
  }
}

