services:
  resource-api:
    image: hopara/resource-api:latest
    platform: linux/amd64
    environment:
      - DISABLE_LOCALSTACK=true
      - CONSUMER_URL=http://resource-consumer:2023
      - LOCAL_STORAGE_PATH=/app/resources
    ports:
      - "2022:2022"
    volumes:
      - ${STORAGE_DIR:-./storage}/resources/icon/customers:/app/resources/icon/customers
      - ${STORAGE_DIR:-./storage}/resources/image/customers:/app/resources/image/customers
      - ${STORAGE_DIR:-./storage}/resources/model/customers:/app/resources/model/customers
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2022/health"]
      interval: 10s
      timeout: 5s
      retries: 12

  resource-consumer:
    image: hopara/resource-consumer:latest
    platform: linux/amd64
    environment:
      - DISABLE_LOCALSTACK=true
      - LOCAL_STORAGE_PATH=/app/resources
    ports:
      - "2023:2023"
    volumes:
      - ${STORAGE_DIR:-./storage}/resources/icon/customers:/app/resources/icon/customers
      - ${STORAGE_DIR:-./storage}/resources/image/customers:/app/resources/image/customers
      - ${STORAGE_DIR:-./storage}/resources/model/customers:/app/resources/model/customers
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2023/health"]
      interval: 10s
      timeout: 5s
      retries: 12

  template:
    image: hopara/template:latest
    environment:
      - DATASET_URL=http://dataset:8000
      - RESOURCE_URL=http://resource-api:2022
    ports:
      - "8089:8089"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8089/health"]
      interval: 10s
      timeout: 5s
      retries: 12

  notification:
    image: hopara/notification:latest
    environment:
      - PORT=8085
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8085/health"]
      interval: 10s
      timeout: 5s
      retries: 12

  db:
    image: hopara/postgres:latest
    volumes:
      - ${STORAGE_DIR:-./storage}/postgres:/var/lib/postgresql/data  
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all  -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kyrix"]
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - "${DB_PORT:-5432}:5432"

  visualization:
    image: hopara/visualization:latest
    environment:
      - PORT=8081
      - DB_HOST=db
      - DB_USER=kyrix
      - DB_PASSWORD=kyrix
      - DATASET_URL=http://host.docker.internal:8000
      - TEMPLATE_URL=http://host.docker.internal:8089
    ports:
      - "8081:8081"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 12

  dataset:
    image: hopara/dataset:latest
    entrypoint: ["java", "-DdatabaseServer=db", "-DdatabaseUsername=kyrix", "-DdatabasePassword=kyrix", "-DdatabaseName=kyrix", "-Dspring.main.allow-bean-definition-overriding=true","-Dspring.jmx.enabled=false","-Dspring.jdbc.getParameterType.ignore=true","-Dlogging.level.kyrix.dataset.row.read=debug","-Xms512m","-Xmx2g", "-jar","/app.jar"]
    ports:
      - "8000:8000"
    environment:
      - notificationEndpoint=http://notification:8085
      - templateEndpoint=http://template:8089
      - databaseServer=db
      - dataFiles.dir=/data/files
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${STORAGE_DIR:-./storage}/data-files:/data/files
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 12

  front:
    image: hopara/front:latest
    ports:
      - "3000:3000"
    depends_on:
      - bff
      - visualization

  bff:
    image: hopara/bff:latest
    environment:
      - DATASET_URL=http://dataset:8000
      - VISUALIZATION_URL=http://visualization:8081
      - TENANT_URL=http://tenant:2021
      - TEMPLATE_URL=http://template:8089
      - RESOURCE_URL=http://resource-api:2022
    ports:
      - "8086:8086"
    depends_on:
      - dataset
      - visualization
      - resource-api
      - template
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 12

  sample-visualization:
    image: busybox
    depends_on:
      bff:
        condition: service_healthy
      resource-api:
        condition: service_healthy
      resource-consumer:
        condition: service_healthy
      template:
        condition: service_healthy
      notification:
        condition: service_healthy
      visualization:
        condition: service_healthy
      dataset:
        condition: service_healthy
    command: ["wget", "--no-verbose", "--tries=3", "--post-data=", "-O", "-", "http://bff:8086/sample-visualization"]
