import React from 'react'

import {
  mdiAccountOutline,
  mdiAlertCircleOutline,
  mdiAlphabetical,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArtboard,
  mdiButtonPointer,
  mdiCalendarMonthOutline,
  mdiChartAreaspline,
  mdiChartLine,
  mdiChartPieOutline,
  mdiCheck,
  mdiCheckboxOutline,
  mdiCheckCircle,
  mdiCircleOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCodeArray,
  mdiCodeJson,
  mdiConnection,
  mdiCubeOutline,
  mdiDatabaseSearch,
  mdiDeleteOutline,
  mdiDotsHorizontal,
  mdiDotsVertical,
  mdiDrag,
  mdiEyeOff,
  mdiEyeOutline,
  mdiFileDocumentOutline,
  mdiFormatListBulletedSquare,
  mdiFormatTextVariant,
  mdiFullscreen,
  mdiHelpCircleOutline,
  mdiHistory,
  mdiImageOutline,
  mdiInformationOutline,
  mdiLayersTripleOutline,
  mdiLightbulbGroupOutline,
  mdiLink,
  mdiLockOpenOutline,
  mdiLockOutline,
  mdiLogout,
  mdiMapMarkerOutline,
  mdiMapOutline,
  mdiMenuDown,
  mdiMenuUp,
  mdiMinus,
  mdiMinusCircle,
  mdiMinusCircleOutline,
  mdiNumeric,
  mdiOpenInNew,
  mdiPentagonOutline,
  mdiPlayOutline,
  mdiPlus,
  mdiPlusCircleOutline,
  mdiTarget,
  mdiText,
  mdiUploadOutline,
  mdiVectorSquare,
  mdiWidgetsOutline,
  mdiTable,
  mdiFormatAlignLeft,
  mdiFormatAlignCenter,
  mdiFormatAlignRight,
  mdiPause,
  mdiGrid,
  mdiRotate360,
  mdiCodeBlockBraces,
} from '@mdi/js'

import Icon from '@mdi/react'

export const pictogrammerIcons = {
  'query': mdiDatabaseSearch,
  'connection': mdiConnection,
  'delete': mdiDeleteOutline,
  'document': mdiFileDocumentOutline,
  'help': mdiHelpCircleOutline,
  'logout': mdiLogout,
  'marker': mdiMapMarkerOutline,
  'color-legends': mdiFormatListBulletedSquare,
  'history': mdiHistory,
  'close': mdiClose,
  'actions': mdiButtonPointer,
  'area-layer': mdiChartAreaspline,
  'image-layer': mdiImageOutline,
  'polygon-layer': mdiVectorSquare,
  'circle-layer': mdiCircleOutline,
  'line-chart-layer': mdiChartLine,
  'text-layer': mdiFormatTextVariant,
  'object-editor-text-layer': mdiText,
  'composite-layer': mdiLayersTripleOutline,
  'arc-layer': mdiChartPieOutline,
  'model-layer': mdiCubeOutline,
  'icon-layer': mdiMapMarkerOutline,
  'upload': mdiUploadOutline,
  'info': mdiInformationOutline,
  'play': mdiPlayOutline,
  'pause': mdiPause,
  'arrow-left': mdiArrowLeft,
  'arrow-right': mdiArrowRight,
  'add': mdiPlus,
  'add-circle': mdiPlusCircleOutline,
  'remove': mdiMinus,
  'remove-circle': mdiMinusCircleOutline,
  'link': mdiLink,
  'visualization-jump': mdiArtboard,
  'zoom-jump': mdiTarget,
  'lock': mdiLockOutline,
  'lock-open': mdiLockOpenOutline,
  'open-in-new': mdiOpenInNew,
  'check': mdiCheck,
  'more-vert': mdiDotsVertical,
  'more-horiz': mdiDotsHorizontal,
  'alert': mdiAlertCircleOutline,
  'menu-up': mdiMenuUp,
  'menu-down': mdiMenuDown,
  'drag': mdiDrag,
  'eye': mdiEyeOutline,
  'eye-off': mdiEyeOff,
  'account': mdiAccountOutline,
  'fullscreen': mdiFullscreen,
  'map-layer': mdiMapOutline,
  'type-string': mdiAlphabetical,
  'type-integer': mdiNumeric,
  'type-string-array': mdiCodeArray,
  'type-string_array': mdiCodeArray,
  'type-json': mdiCodeJson,
  'type-datetime': mdiCalendarMonthOutline,
  'type-boolean': mdiCheckboxOutline,
  'type-geometry': mdiPentagonOutline,
  'ok': mdiCheckCircle,
  'nok': mdiCloseCircle,
  'not-defined': mdiMinusCircle,
  'lightbulb-group': mdiLightbulbGroupOutline,
  'template-layer': mdiWidgetsOutline,
  'table': mdiTable,
  'align-left': mdiFormatAlignLeft,
  'align-center': mdiFormatAlignCenter,
  'align-right': mdiFormatAlignRight,
  'grid': mdiGrid,
  'rotate': mdiRotate360,
  'code-block': mdiCodeBlockBraces,
}

export const pictogrammerIconKeys = Object.keys(pictogrammerIcons) as PictogrammerIconKey[]

export type PictogrammerIconKey = keyof typeof pictogrammerIcons

interface Props {
  size: number;
  icon: PictogrammerIconKey;
  color?: string;
  style?: any
}

export const PictogrammerIcon = (props: Props): React.ReactElement => {
  const iconKey = pictogrammerIcons[props.icon] as any
  if (iconKey) {
    return <Icon path={iconKey} size={props.size / 24} color={props.color} data-testid={`${props.icon}-icon`} style={props.style}/>
  }
  throw new Error(`Icon ${props.icon} not found`)
}

