databaseServer=${DATABASE_SERVER:localhost}
databaseUsername=hopara
databasePassword=hopara
databaseName=hopara
logging.level.hopara.dataset.row.read=debug

# Singlestore
#databaseServer=172.30.105.1
#databaseType=SINGLESTORE