databaseServer=${DATABASE_SERVER:localhost}
databaseUsername=kyrix
databasePassword=kyrix
databaseName=kyrix
logging.level.hopara.dataset.row.read=debug

# Singlestore
#databaseServer=172.30.105.1
#databaseType=SINGLESTORE