# spring ignores spring.jdbc.getParameterType.ignore in the properties. It's necessary to set it in JVM args.
spring.jdbc.getParameterType.ignore=true
spring.data.jdbc.repositories.enabled=false
spring.main.allow-bean-definition-overriding=true

# Flyway
spring.flyway.connect-retries=18
spring.flyway.connect-retries-interval=5
flywayConnectRetries=12

server.port=8000

# database
databaseServer=localhost
databaseUsername=hopara
databasePassword=hopara
databaseName=hopara

auth.enabled=false
dataFiles.storage=fs

#compression
server.compression.enabled=true

# spring cloud
spring.cloud.aws.enabled=false
spring.cloud.aws.s3.enabled=false

cloud.aws.region.static=us-east-1
cloud.aws.stack.auto=false
logging.level.com.amazonaws.util.EC2MetadataUtils=error
com.amazonaws.sdk.disableEc2Metadata=
cloud.aws.credentials.useDefaultAwsCredentialsChain = true

# log level
#logging.level.org.springframework=TRACE
#logging.level.org.springframework.web=TRACE

notificationEndpoint=http://localhost:8085
templateEndpoint=http://localhost:8089
datasetEndpoint=http://localhost:8000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8088/.well-known/dev.json
env=dev
dataFiles.dir=dataset-data-files
dataSource.passwordStrategy=database
server.tomcat.mbeanregistry.enabled=true
server.tomcat.max-threads=300
server.tomcat.keep-alive-timeout=610000
server.max-http-header-size=16KB
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-message=always
spring.servlet.multipart.max-file-size=10MB